language: ruby

rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - jruby-18mode
  - jruby-19mode
  - rbx

before_install:
  - gem update --system 2.1.11
  - gem --version

before_script:
  - rake compile

script: bundle exec rspec -c spec/

